apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f7q3943e2-python
  janus-idp.io/tekton: f7q3943e2-python
  backstage.io/kubernetes-id: f7q3943e2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f7q3943e2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
